/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package packnews;

public class App {
    public String getGreeting() {
        return "Salve world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
